LEX = lex
YACC = yacc -d

CC = cc

conf: y.tab.o lex.yy.o
	$(CC) -o conf y.tab.o lex.yy.o -ll -lm 

lex.yy.o: lex.yy.c y.tab.h

y.tab.c y.tab.h: conf.y
	$(YACC) -v conf.y

lex.yy.c: conf.l
	$(LEX) conf.l

clean:
	-rm -f *.o lex.yy.c *.tab.*  conf *.output
